
engine:
  max_step: 5 #最多连续进行n次action
  max_self_reflexion_step: 3
  code_model: gpt-4o
  code_temperature: 0.8
  feedback_model: gpt-4o
  feedback_temperature: 0.8
  enable_feedback: True
  json_mode: True
  feedback_json_mode: True

ocr:
  method: pytesseract # pytesseract, easyocr, surya

code_env:
  work_directory: ./code_workspace/
  max_entry_nums_for_level: 20
  data_path: /Users/user/Downloads/git_clone/VisAgent/assets/vis_data/McDonald_financial_statements/McDonalds_Financial_Statements.csv

recorder:
  record_dir: "history_data_qwen-turbo"

request:
  default_model: "gpt-4o"
  default_timeout: 600
  gpt:
    api_key: "sk-vAjSo8FwpoiMM01FEfB337D75e6440848e8b89Aa18Ca3810"
    base_url: "https://aihubmix.com/v1"
    max_tokens: 1000
    temperature: 0.8
  gpt4v:
    api_key: "sk-vAjSo8FwpoiMM01FEfB337D75e6440848e8b89Aa18Ca3810"
    base_url: "https://aihubmix.com/v1"
    max_tokens: 1000
    temperature: 0.8
  claude:
    api_key: "api_key"
    max_tokens: 1000
    temperature: 0.8
    request_timeout: 60

