
engine:
  max_step: 4 #最多连续进行n+1次action

ocr:
  method: pytesseract # pytesseract, easyocr, surya

code_env:
  work_directory: ./code_workspace/
  max_entry_nums_for_level: 20
  data_path: /Users/user/Downloads/git_clone/VisAgent/assets/vis_data/McDonald_financial_statements/McDonalds_Financial_Statements.csv

recorder:
  record_dir: "history_data"

request:
  default_model: "gpt-4o"
  default_timeout: 600
  gpt:
    api_key: "sk-vAjSo8FwpoiMM01FEfB337D75e6440848e8b89Aa18Ca3810"
    base_url: "https://aihubmix.com/v1"
    max_tokens: 1000
    temperature: 0.8
  gpt4v:
    # api_key: "sk-dMEct6QNGiA505piB10c6952112549779466AdB711801dEc"
    # base_url: "https://aihubmix.com/v1"
    api_key: "sk-vAjSo8FwpoiMM01FEfB337D75e6440848e8b89Aa18Ca3810"
    base_url: "https://aihubmix.com/v1"
    max_tokens: 1000
    temperature: 0.8
  claude:
    api_key: "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"
    max_tokens: 1000
    temperature: 0.8
    request_timeout: 60

